spring:
  application:
    name: delivery-service
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///delivery_db
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: delivery-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# Configuration des topics Kafka
kafka:
  topics:
    booking-created: booking-created
    time-slot-created: time-slot-created
    time-slot-booked: time-slot-booked
    time-slot-released: time-slot-released
